name: AWS Operations

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decrypt SOPS-encrypted Secret
        run: |
          wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          chmod +x sops-v3.7.1.linux
          ./sops-v3.7.1.linux -d --kms "arn:aws:kms:us-east-1:934076056444:key/c28a6a3b-2904-4c9f-b8b8-c625a64e4e63" sops/my-aws-account/secrets.json > decrypted_secret.json

      - name: Configure AWS CLI with Decrypted Secret
        run: |
          decrypted_secret=$(cat decrypted_secret.json)
          aws configure set aws_access_key_id "$(echo $decrypted_secret | jq -r '.aws_access_key_id')"
          aws configure set aws_secret_access_key "$(echo $decrypted_secret | jq -r '.aws_secret_access_key')"
          aws configure set default.region "us-east-1"  # Update with your desired region

      - name: Create new KMS key
        run: |
          aws kms create-key --description "My new key" --output text
